// <auto-generated />
using System;
using AutomotiveIntelligence.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomotiveIntelligence.Data.Migrations
{
    [DbContext(typeof(AutomotiveIntelligenceDbContext))]
    [Migration("20260921160618_AddPamaProduction")]
    partial class AddPamaProduction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId", "Name")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Lahore",
                            ProvinceId = 1
                        },
                        new
                        {
                            CityId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Rawalpindi",
                            ProvinceId = 1
                        },
                        new
                        {
                            CityId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Faisalabad",
                            ProvinceId = 1
                        },
                        new
                        {
                            CityId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Multan",
                            ProvinceId = 1
                        },
                        new
                        {
                            CityId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Gujranwala",
                            ProvinceId = 1
                        },
                        new
                        {
                            CityId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Karachi",
                            ProvinceId = 2
                        },
                        new
                        {
                            CityId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Hyderabad",
                            ProvinceId = 2
                        },
                        new
                        {
                            CityId = 8,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Peshawar",
                            ProvinceId = 3
                        },
                        new
                        {
                            CityId = 9,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Abbottabad",
                            ProvinceId = 3
                        },
                        new
                        {
                            CityId = 10,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Quetta",
                            ProvinceId = 4
                        },
                        new
                        {
                            CityId = 11,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Islamabad",
                            ProvinceId = 5
                        });
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Comparison", b =>
                {
                    b.Property<long>("ComparisonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ComparisonId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ComparisonId");

                    b.HasIndex("UserId");

                    b.ToTable("Comparisons", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.ComparisonVehicle", b =>
                {
                    b.Property<long>("ComparisonId")
                        .HasColumnType("bigint");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("ComparisonId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ComparisonId", "DisplayOrder");

                    b.ToTable("ComparisonVehicles", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CountryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Code = "PK",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Pakistan"
                        });
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.DataImport", b =>
                {
                    b.Property<long>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportId"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImportStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RecordsDuplicated")
                        .HasColumnType("int");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("RecordsRejected")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ImportId");

                    b.HasIndex("SourceId");

                    b.HasIndex("StartedDate");

                    b.ToTable("DataImports", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.DataSource", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceId"));

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataSources", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Favorite", b =>
                {
                    b.Property<long>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FavoriteId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("UserId", "VehicleId")
                        .IsUnique();

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Listing", b =>
                {
                    b.Property<long>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ListingId"));

                    b.Property<decimal>("AskingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ListingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ListingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SellerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.HasIndex("CityId");

                    b.HasIndex("ListingDate");

                    b.HasIndex("ListingStatus");

                    b.HasIndex("SourceId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Make", b =>
                {
                    b.Property<int>("MakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakeId"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MakeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Makes", (string)null);

                    b.HasData(
                        new
                        {
                            MakeId = 1,
                            Country = "Japan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Toyota"
                        },
                        new
                        {
                            MakeId = 2,
                            Country = "Japan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Honda"
                        },
                        new
                        {
                            MakeId = 3,
                            Country = "Japan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Suzuki"
                        },
                        new
                        {
                            MakeId = 4,
                            Country = "South Korea",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "KIA"
                        },
                        new
                        {
                            MakeId = 5,
                            Country = "South Korea",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Hyundai"
                        });
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.MarketPrice", b =>
                {
                    b.Property<long>("MarketPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MarketPriceId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("ConditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ObservationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ObservedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MarketPriceId");

                    b.HasIndex("CityId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("ObservationDate");

                    b.HasIndex("SourceId");

                    b.HasIndex("VariantId", "CityId", "Year");

                    b.ToTable("MarketPrices", (string)null);

                    b.HasData(
                        new
                        {
                            MarketPriceId = 1L,
                            CityId = 1,
                            ConditionId = 2,
                            CreatedDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mileage = 45000,
                            ObservationDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ObservedPrice = 7200000m,
                            VariantId = 1,
                            Year = 2022
                        },
                        new
                        {
                            MarketPriceId = 2L,
                            CityId = 1,
                            ConditionId = 2,
                            CreatedDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mileage = 52000,
                            ObservationDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ObservedPrice = 7000000m,
                            VariantId = 1,
                            Year = 2022
                        },
                        new
                        {
                            MarketPriceId = 3L,
                            CityId = 1,
                            ConditionId = 1,
                            CreatedDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mileage = 30000,
                            ObservationDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ObservedPrice = 7500000m,
                            VariantId = 1,
                            Year = 2022
                        },
                        new
                        {
                            MarketPriceId = 4L,
                            CityId = 1,
                            ConditionId = 3,
                            CreatedDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mileage = 70000,
                            ObservationDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ObservedPrice = 6700000m,
                            VariantId = 1,
                            Year = 2022
                        },
                        new
                        {
                            MarketPriceId = 5L,
                            CityId = 1,
                            ConditionId = 2,
                            CreatedDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mileage = 60000,
                            ObservationDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ObservedPrice = 6900000m,
                            VariantId = 1,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.MarketSnapshot", b =>
                {
                    b.Property<long>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SnapshotId"));

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DemandScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ListingCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MaximumPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MedianPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("SnapshotId");

                    b.HasIndex("CityId");

                    b.HasIndex("VariantId", "CityId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("MarketSnapshots", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("BodyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ModelId");

                    b.HasIndex("MakeId", "Name")
                        .IsUnique();

                    b.ToTable("Models", (string)null);

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            BodyType = "Sedan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            ModelId = 2,
                            BodyType = "Sedan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 1,
                            Name = "Yaris"
                        },
                        new
                        {
                            ModelId = 3,
                            BodyType = "SUV",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 1,
                            Name = "Fortuner"
                        },
                        new
                        {
                            ModelId = 4,
                            BodyType = "Sedan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 2,
                            Name = "Civic"
                        },
                        new
                        {
                            ModelId = 5,
                            BodyType = "Sedan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 2,
                            Name = "City"
                        },
                        new
                        {
                            ModelId = 6,
                            BodyType = "Hatchback",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 3,
                            Name = "Alto"
                        },
                        new
                        {
                            ModelId = 7,
                            BodyType = "Hatchback",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 3,
                            Name = "Cultus"
                        },
                        new
                        {
                            ModelId = 8,
                            BodyType = "Hatchback",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 3,
                            Name = "Swift"
                        },
                        new
                        {
                            ModelId = 9,
                            BodyType = "SUV",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 4,
                            Name = "Sportage"
                        },
                        new
                        {
                            ModelId = 10,
                            BodyType = "Hatchback",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 4,
                            Name = "Picanto"
                        },
                        new
                        {
                            ModelId = 11,
                            BodyType = "SUV",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 5,
                            Name = "Tucson"
                        },
                        new
                        {
                            ModelId = 12,
                            BodyType = "Sedan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MakeId = 5,
                            Name = "Elantra"
                        });
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.PamaProduction", b =>
                {
                    b.Property<long>("PamaProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PamaProductionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("ObservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductionUnits")
                        .HasColumnType("int");

                    b.Property<int>("SalesUnits")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PamaProductionId");

                    b.HasIndex("ImportId");

                    b.HasIndex("ObservationDate");

                    b.HasIndex("MakeId", "Year", "Month");

                    b.HasIndex("SourceId", "Year", "Month");

                    b.ToTable("PamaProductions", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.PriceAlert", b =>
                {
                    b.Property<long>("PriceAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PriceAlertId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTriggeredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("PriceAlertId");

                    b.HasIndex("CityId");

                    b.HasIndex("IsActive");

                    b.HasIndex("VariantId");

                    b.HasIndex("UserId", "VariantId");

                    b.ToTable("PriceAlerts", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            CountryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Punjab"
                        },
                        new
                        {
                            ProvinceId = 2,
                            CountryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Sindh"
                        },
                        new
                        {
                            ProvinceId = 3,
                            CountryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Khyber Pakhtunkhwa"
                        },
                        new
                        {
                            ProvinceId = 4,
                            CountryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Balochistan"
                        },
                        new
                        {
                            ProvinceId = 5,
                            CountryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Islamabad Capital Territory"
                        });
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Valuation", b =>
                {
                    b.Property<long>("ValuationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ValuationId"));

                    b.Property<decimal?>("AskingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("ConditionId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<decimal>("MaximumPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RecommendedBuyingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RecommendedNegotiationPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ValuationMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ValuationId");

                    b.HasIndex("CityId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("UserId");

                    b.HasIndex("VariantId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Valuations", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.ValuationFactor", b =>
                {
                    b.Property<long>("ValuationFactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ValuationFactorId"));

                    b.Property<decimal?>("AdjustmentPercentage")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("AdjustmentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FactorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FactorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ValuationId")
                        .HasColumnType("bigint");

                    b.HasKey("ValuationFactorId");

                    b.HasIndex("ValuationId");

                    b.ToTable("ValuationFactors", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Variant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriveType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EngineCapacity")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VariantId");

                    b.HasIndex("ModelId", "Name")
                        .IsUnique();

                    b.ToTable("Variants", (string)null);

                    b.HasData(
                        new
                        {
                            VariantId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 1800,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 1,
                            Name = "Altis X",
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            VariantId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 1800,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 1,
                            Name = "Altis Grande",
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            VariantId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 1300,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 2,
                            Name = "GLI",
                            SeatingCapacity = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            VariantId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 1300,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 2,
                            Name = "ATIV",
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            VariantId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "4WD",
                            EngineCapacity = 2700,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 3,
                            Name = "2.7 V",
                            SeatingCapacity = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            VariantId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 1500,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 4,
                            Name = "1.5 Turbo",
                            SeatingCapacity = 5,
                            Transmission = "CVT"
                        },
                        new
                        {
                            VariantId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 1200,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 5,
                            Name = "1.2",
                            SeatingCapacity = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            VariantId = 8,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 660,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 6,
                            Name = "VXR",
                            SeatingCapacity = 4,
                            Transmission = "Manual"
                        },
                        new
                        {
                            VariantId = 9,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 660,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 6,
                            Name = "VXL AGS",
                            SeatingCapacity = 4,
                            Transmission = "AMT"
                        },
                        new
                        {
                            VariantId = 10,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 998,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 7,
                            Name = "VXL",
                            SeatingCapacity = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            VariantId = 11,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 1200,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 8,
                            Name = "GL",
                            SeatingCapacity = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            VariantId = 12,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 2000,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 9,
                            Name = "FWD",
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            VariantId = 13,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 1000,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 10,
                            Name = "1.0",
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            VariantId = 14,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 2000,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 11,
                            Name = "FWD",
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            VariantId = 15,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveType = "FWD",
                            EngineCapacity = 2000,
                            FuelType = "Petrol",
                            IsActive = true,
                            ModelId = 12,
                            Name = "GL",
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ConditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("HasAccidentHistory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerCount")
                        .HasColumnType("int");

                    b.Property<int?>("RegistrationYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("VariantId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.VehicleCondition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ConditionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleConditions", (string)null);

                    b.HasData(
                        new
                        {
                            ConditionId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Very well maintained vehicle with minimal signs of use.",
                            IsActive = true,
                            Name = "Excellent",
                            Score = 95m
                        },
                        new
                        {
                            ConditionId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Well maintained vehicle with normal signs of use.",
                            IsActive = true,
                            Name = "Good",
                            Score = 85m
                        },
                        new
                        {
                            ConditionId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vehicle with normal wear and some maintenance requirements.",
                            IsActive = true,
                            Name = "Average",
                            Score = 70m
                        },
                        new
                        {
                            ConditionId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vehicle with noticeable wear and maintenance requirements.",
                            IsActive = true,
                            Name = "Fair",
                            Score = 55m
                        },
                        new
                        {
                            ConditionId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vehicle requiring significant maintenance or repairs.",
                            IsActive = true,
                            Name = "Poor",
                            Score = 35m
                        });
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.VehicleSpecifications", b =>
                {
                    b.Property<int>("VehicleSpecificationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleSpecificationsId"));

                    b.Property<int?>("AirbagCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BootSpace")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriveType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EngineCapacity")
                        .HasColumnType("int");

                    b.Property<decimal?>("FuelTankCapacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("FuelType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GroundClearance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("HasABS")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasInfotainment")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasStabilityControl")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasSunroof")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasTractionControl")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Height")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("int");

                    b.Property<decimal?>("Length")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("Torque")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Wheelbase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Width")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("VehicleSpecificationsId");

                    b.HasIndex("VariantId")
                        .IsUnique();

                    b.ToTable("VehicleSpecifications", (string)null);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.City", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Comparison", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.ComparisonVehicle", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Comparison", null)
                        .WithMany()
                        .HasForeignKey("ComparisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.DataImport", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Listing", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.MarketPrice", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.VehicleCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.MarketSnapshot", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Variant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Model", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Make", null)
                        .WithMany()
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.PamaProduction", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.DataImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Make", "Make")
                        .WithMany()
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.PriceAlert", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Variant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Province", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Valuation", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.VehicleCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Variant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.ValuationFactor", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Valuation", null)
                        .WithMany()
                        .HasForeignKey("ValuationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Variant", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.VehicleCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Variant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutomotiveIntelligence.Domain.Entities.VehicleSpecifications", b =>
                {
                    b.HasOne("AutomotiveIntelligence.Domain.Entities.Variant", null)
                        .WithOne()
                        .HasForeignKey("AutomotiveIntelligence.Domain.Entities.VehicleSpecifications", "VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
