<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutomotiveIntelligence.Application\AutomotiveIntelligence.Application.csproj" />
    <ProjectReference Include="..\AutomotiveIntelligence.Data\AutomotiveIntelligence.Data.csproj" />
    <ProjectReference Include="..\AutomotiveIntelligence.Domain\AutomotiveIntelligence.Domain.csproj" />
  </ItemGroup>

</Project>
