<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutomotiveIntelligence.Domain\AutomotiveIntelligence.Domain.csproj" />
    <ProjectReference Include="..\AutomotiveIntelligence.Shared\AutomotiveIntelligence.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
  </ItemGroup>

</Project>
